import avtar from './../assets/avtar.jpg';

export default [
  {
    "value": "Darren Seiden",
    "text": "Darren Seiden",
    "email": "darren.seiden@yapsody.com",
    "image": "https://media-exp1.licdn.com/dms/image/C5603AQFH14lLggoJnQ/profile-displayphoto-shrink_200_200/0?e=1608768000&v=beta&t=f2VbmIrRXVOczvq8RCtiY0Mrt65YoZOEl5ptD8mrJpA",
    "role": "Founder, Managing Director",
    "locality": "Rapid City, SD",
    "country": "USA",
    "linkedin": "https://www.linkedin.com/in/darrenseiden/"
  },
  {
    "value": "Vinay Chavan",
    "text": "Vinay Chavan",
    "email": "vinay.chavan@yapsody.com",
    "image": "https://www.gravatar.com/avatar/cc9d89237582f9289f2038d24b6aab95?s=180&d=identicon",
    "role": "CEO, Director, Engineering Head",
    "locality": "Mumbai, MH",
    "country": "India",
    "twitter": "davinc",
    "facebook": "vinay.chavan",
    "linkedin": "https://www.linkedin.com/in/vinaychavan",
    "gitlab": "vinay.chavan",
    "youtube": "https://www.youtube.com/channel/UCO1IGgj9s8F1vPpCGXMzg8Q",
    "site": "https://www.vinaychavan.com",
    "story": "",
    "dob": "1985-10-22",
    "doj": ""
  },
  {
    "value": "Sanjiv Pandey",
    "text": "Sanjiv Pandey",
    "email": "sanjiv.pandey@yapsody.com",
    "image": "https://media-exp1.licdn.com/dms/image/C5103AQFfMPsHuclzAQ/profile-displayphoto-shrink_200_200/0?e=1608768000&v=beta&t=VUt0SHxIcKLjthJFBnVk1HbV2yeWZ2Kz3wYk7-mtgLI",
    "role": "Director, Operations Head",
    "locality": "Mumbai, MH",
    "country": "India",
    "facebook": "sanjiv.pandey.7",
    "linkedin": "https://www.linkedin.com/in/sanjeev-pandey-428a1353/"
  },
  {
    "value": "Abhinav Sridhar",
    "text": "Abhinav Sridhar",
    "email": "abhinav.sridhar@yapsody.com",
    "image": "https://media-exp1.licdn.com/dms/image/C5103AQGvi4HkxkM6Fg/profile-displayphoto-shrink_200_200/0?e=1608768000&v=beta&t=gPJPuPN3Vz5TlucmYp_4iRM4Iq1-5zxmXHQqEm69CKE",
    "role": "Business Strategy Head",
    "locality": "Toronto",
    "country": "Canada",
    "facebook": "abhinav.sridhar",
    "linkedin": "https://www.linkedin.com/in/abhinav-sridhar/"
  },
  {
    "value": "Govindraj Shetty",
    "text": "Govindraj Shetty",
    "email": "govindraj.shetty@yapsody.com",
    "image": "https://media-exp1.licdn.com/dms/image/C5103AQGuYcNybt5Udg/profile-displayphoto-shrink_200_200/0?e=1608768000&v=beta&t=CdTSpALJTXQyJEl-_d8RmlBFvF5kB3-SsV4WHIRk6t4",
    "role": "Support Center Manager",
    "locality": "Mumbai, MH",
    "country": "India",
    "facebook": "govindraj.shetty",
    "linkedin": "https://www.linkedin.com/in/govindraj%2Dshetty%2Dhdi%2Dscm%2Da962b614/"
  },
  {
    "value": "Zeenat Crasto",
    "text": "Zeenat Crasto",
    "email": "zeenat.crasto@yapsody.com",
    "image": avtar,
    "role": "People Experience Manager",
    "locality": "Mumbai, MH",
    "country": "India",
    "facebook": "Zeenette.Crasto",
    "linkedin": "https://www.linkedin.com/in/zeenat-crasto-11388927/"
  },
  {
    "value": "Ashwinee Datar",
    "text": "Ashwinee Datar",
    "email": "ashwinee.datar@yapsody.com",
    "image": "https://media-exp1.licdn.com/dms/image/C5603AQE2xr6OKOaBtg/profile-displayphoto-shrink_200_200/0?e=1608768000&v=beta&t=U-xxKbdR5L8EAJ8p-iqRQ6treA5P3hwLTxB1fVM-GpE",
    "role": "Project Coordinator",
    "locality": "Mumbai, MH",
    "country": "India",
    "twitter": "ashwineedatar",
    "linkedin": "https://www.linkedin.com/in/ashwinee-datar-kar-25377322/"
  },
  {
    "value": "Prajakta Shah",
    "text": "Prajakta Shah",
    "email": "prajakta.shah@yapsody.com",
    "image": "https://media-exp1.licdn.com/dms/image/C5603AQEWVqPzVz10mg/profile-displayphoto-shrink_200_200/0?e=1608768000&v=beta&t=Xl8M4NFSAHD7B11BZBpOQBqaMjYLfrNGNZpLymW-8XM",
    "role": "Business Analyst",
    "locality": "Mumbai, MH",
    "country": "India",
    "twitter": "praj_sawshah",
    "linkedin": "https://www.linkedin.com/in/prajakta-shah-7766071a7/"
  },
  {
    "value": "Rohit Gadhiya",
    "text": "Rohit Gadhiya",
    "email": "rohit.gadhiya@yapsody.com",
    "image": "https://media-exp1.licdn.com/dms/image/C4D03AQHFS-NCGQH9eg/profile-displayphoto-shrink_200_200/0?e=1608768000&v=beta&t=Frj6JuyVyvFrXZrXSeDmH7v0iix9yZutW_dJeP9YcNc",
    "role": "Business Analyst",
    "locality": "Mumbai, MH",
    "country": "India",
    "facebook": "RohitGadhiya91939",
    "linkedin": "https://www.linkedin.com/in/rohit-gadhiya-47994b24/"
  },
  {
    "value": "Shailesh Kharat",
    "text": "Shailesh Kharat",
    "email": "shailesh.kharat@yapsody.com",
    "image": "https://media-exp1.licdn.com/dms/image/C5603AQE_XomJXVt6LQ/profile-displayphoto-shrink_200_200/0?e=1608768000&v=beta&t=bgXoEoifnxvtuKv2VSoim_gmXS89wgXKmL03LdyG09Y",
    "role": "Business Analyst",
    "locality": "Mumbai, MH",
    "country": "India",
    "facebook": "srk2617",
    "linkedin": "https://www.linkedin.com/in/shailesh-kharat-13b470135/"
  },
  {
    "value": "Nishi Mehta",
    "text": "Nishi Mehta",
    "email": "nishi.mehta@yapsody.com",
    "image": "https://media-exp1.licdn.com/dms/image/C5103AQFeNIwdkPB6vw/profile-displayphoto-shrink_200_200/0?e=1608768000&v=beta&t=MHpa0uIURbY1qjDMrbRItyBOtKBkUjnJ0z7WTMEc7cg",
    "role": "Sr QA Engineer",
    "locality": "Mumbai, MH",
    "country": "India",
    "facebook": "nishi.jain.31924",
    "linkedin": "https://www.linkedin.com/in/nishi-mehta-38706349/"
  },
  {
    "value": "Manish Gupta",
    "text": "Manish Gupta",
    "email": "manish.gupta@yapsody.com",
    "image": "https://media-exp1.licdn.com/dms/image/C5103AQG3bsOFrLMFPg/profile-displayphoto-shrink_200_200/0?e=1608768000&v=beta&t=kgAWXoQXMmBIc2vv4latwDGrwOACVymuBLXT17fPVKk",
    "role": "Sr Software Engineer",
    "locality": "Mumbai, MH",
    "country": "India",
    "facebook": "manish.g.gupta",
    "twitter": "ManishG20376925",
    "linkedin": "https://www.linkedin.com/in/manish011994/"
  },
  {
    "value": "Abhijeet D'Britto",
    "text": "Abhijeet D'Britto",
    "email": "abhijeet.dbritto@yapsody.com",
    "image": "https://media-exp1.licdn.com/dms/image/C5103AQHczVILkB-Sdw/profile-displayphoto-shrink_200_200/0?e=1608768000&v=beta&t=j53yJsVpH7SiUTe8_RiX4zPZMBlgP6jIf4u14H-rCb4",
    "role": "Sr Software Engineer",
    "locality": "Virar, MH",
    "country": "India",
    "twitter": "AbhijeetDbritto",
    "linkedin": "https://www.linkedin.com/in/abhijeet-d-britto-08913153/"
  },
  {
    "value": "Aniket Belwalkar",
    "text": "Aniket Belwalkar",
    "email": "aniket.belwalkar@yapsody.com",
    "image": "https://media-exp1.licdn.com/dms/image/C5103AQGtB2LaOOX-qg/profile-displayphoto-shrink_200_200/0?e=1608768000&v=beta&t=iPb86AuvOVcRg8zJrqFYgm6xSpo5WUCR-E8JZD0NjNc",
    "role": "Sr Software Engineer",
    "locality": "Mumbai, MH",
    "country": "India",
    "facebook": "abelwalkar",
    "twitter": "aniketbel",
    "linkedin": "https://www.linkedin.com/in/abelwalkar/"
  },
  {
    "value": "Keval Sompura",
    "text": "Keval Sompura",
    "email": "keval.sompura@yapsody.com",
    "image": "https://media-exp1.licdn.com/dms/image/C5603AQE1wumLhMd3GA/profile-displayphoto-shrink_200_200/0?e=1609372800&v=beta&t=AO7l-0eF7qckP-pdA7QhZA87s2htNK0F0qIw5ZYUEMs",
    "role": "Software Engineer",
    "locality": "Mumbai, MH",
    "country": "India",
    "linkedin": "https://www.linkedin.com/in/kevalsompura/"
  },
  {
    "value": "Digvijay Mhasaye",
    "text": "Digvijay Mhasaye",
    "email": "digvijay.mhasaye@yapsody.com",
    "image": "https://media-exp1.licdn.com/dms/image/C5103AQEwmMeGOkwrXQ/profile-displayphoto-shrink_200_200/0?e=1609372800&v=beta&t=rPsS6mL8QxIOm2QE7zUFLxFakP6jz5U_9PcgM73NANQ",
    "role": "Software Engineer",
    "locality": "Mumbai, MH",
    "country": "India",
    "linkedin": "https://www.linkedin.com/in/digvijay-mhasaye-29424ab7/"
  },
  {
    "value": "Yash Patil",
    "text": "Yash Patil",
    "email": "yash.patil@yapsody.com",
    "image": "https://media-exp1.licdn.com/dms/image/C5603AQFCC7pSCOAyoA/profile-displayphoto-shrink_200_200/0?e=1609372800&v=beta&t=y-jfdu8k1vrvtCbUe4Z0Cy7phckeKf2KfD8f0vX6VKw",
    "role": "Software Engineer",
    "locality": "Mumbai, MH",
    "country": "India",
    "facebook": "yashpatil810",
    "twitter": "yashpatil810",
    "linkedin": "https://www.linkedin.com/in/yash-patil-656719106/"
  },
  {
    "value": "Prince Singh",
    "text": "Prince Singh",
    "email": "prince.singh@yapsody.com",
    "image": "https://media-exp1.licdn.com/dms/image/C5603AQGt-Mlu54WKkw/profile-displayphoto-shrink_200_200/0?e=1609372800&v=beta&t=Wpxcc_Cd-0AA_veazCpODeoKjAJWjI7RzfShhMrHn7U",
    "role": "Software Engineer",
    "locality": "Mumbai, MH",
    "country": "India",
    "linkedin": "https://www.linkedin.com/in/prince-singh-b34a45128/"
  },
  {
    "value": "Amit Khandelwal",
    "text": "Amit Khandelwal",
    "email": "amit.khandelwal@yapsody.com",
    "image": "https://media-exp1.licdn.com/dms/image/C5103AQEQG0Pfnih2aw/profile-displayphoto-shrink_200_200/0?e=1609372800&v=beta&t=DE4peeay3TNjyaW03vHwDxPu0irPzLPtAqG56YgyB18",
    "role": "QA Engineer",
    "locality": "Mumbai, MH",
    "country": "India",
    "facebook": "amit.khandelwal.73932",
    "linkedin": "https://www.linkedin.com/in/amit-khandelwal-402849160/"
  },
  {
    "value": "Malika Ansari",
    "text": "Malika Ansari",
    "email": "malika.ansari@yapsody.com",
    "image": "https://media-exp1.licdn.com/dms/image/C4E03AQHVFiOg4L2X9w/profile-displayphoto-shrink_200_200/0?e=1609372800&v=beta&t=XOpbSu31Cp7n2WBUBjdC1yz_bg56Hqy3JPMEgv95GWQ",
    "role": "Software Engineer",
    "locality": "Mumbai, MH",
    "country": "India",
    "facebook": "ansari.mul",
    "twitter": "forever_malikaa",
    "linkedin": "https://www.linkedin.com/in/malika-ansari-b89a81137/"
  },
  {
    "value": "Kaleem Elahi",
    "text": "Kaleem Elahi",
    "email": "kaleem.shaikh@yapsody.com",
    "image": "https://media-exp1.licdn.com/dms/image/C4D03AQEvYkvLOnxlLw/profile-displayphoto-shrink_200_200/0?e=1609372800&v=beta&t=fsF3ULXIP44KYoq_umb-Myrw9frNGW73wLmK3FBwVns",
    "role": "Software Engineer",
    "locality": "Gujrat",
    "country": "India",
    "facebook": "shaikh9996",
    "twitter": "kaleem__elahi",
    "linkedin": "https://www.linkedin.com/in/kaleem-elahi/"
  },
  {
    "value": "Arpit Yadav",
    "text": "Arpit Yadav",
    "email": "arpit.yadav@yapsody.com",
    "image": "https://media-exp1.licdn.com/dms/image/C4E03AQEE8TD_-IcTbA/profile-displayphoto-shrink_200_200/0?e=1609372800&v=beta&t=9yJOhNNYZqe7wqZPxQCw5Asw31WM6kwCqGBZrF5ax3w",
    "role": "Software Engineer",
    "locality": "Mumbai, MH",
    "country": "India",
    "twitter": "arpitabsyadav",
    "linkedin": "https://www.linkedin.com/in/arpitabsyadav/"
  },
  {
    "value": "Abhishekh Chauhan",
    "text": "Abhishekh Chauhan",
    "email": "abhishekh.chauhan@yapsody.com",
    "image": "https://media-exp1.licdn.com/dms/image/C5103AQF5xCIClsPeGQ/profile-displayphoto-shrink_200_200/0?e=1609372800&v=beta&t=Z0Z4oYSXiAZVVbhkhBAH0P3fVxtbBywS8zRhT1UGjOc",
    "role": "UX Designer",
    "locality": "Thane, MH",
    "country": "India",
    "linkedin": "https://www.linkedin.com/in/abhishekh-chauhan/"
  },
  {
    "value": "Shubham Nikhare",
    "text": "Shubham Nikhare",
    "email": "shubham.nikhare@yapsody.com",
    "image": "https://media-exp1.licdn.com/dms/image/C5103AQEil5bhGL3L5w/profile-displayphoto-shrink_200_200/0?e=1609372800&v=beta&t=hDgrWZQHuEDSd-c6bxkMdLhosEvzEXqPqQd79cPUj30",
    "role": "UI Designer",
    "locality": "Nagpur, MH",
    "country": "India",
    "facebook": "Shubham.Nikhare.5",
    "twitter": "shubhamn16",
    "linkedin": "https://www.linkedin.com/in/shubham-nikhare-9595b7153/"
  },
  {
    "value": "Divya Singh",
    "text": "Divya Singh",
    "email": "divya.singh@yapsody.com",
    "image":avtar,
    "role": "UI Designer",
    "locality": "Noida, UP",
    "country": "India"
  },
  {
    "value": "Bhavik Kiri",
    "text": "Bhavik Kiri",
    "email": "bhavik.kiri@yapsody.com",
    "image": "https://media-exp1.licdn.com/dms/image/C5103AQEOI7K2wOFooA/profile-displayphoto-shrink_200_200/0?e=1609372800&v=beta&t=NlsPv8TUQbTqIlZ7WHv_UI0lgvP5cuaoFRtWYay-ocM",
    "role": "Software Engineer",
    "locality": "Mumbai, MH",
    "country": "India",
    "facebook": "bhavik.kiri.9",
    "twitter": "bhavik_kiri",
    "linkedin": "https://www.linkedin.com/in/bhavik-kiri-ab932333/"
  },
  {
    "value": "Dheeraj Bari",
    "text": "Dheeraj Bari",
    "email": "dheeraj.bari@yapsody.com",
    "image": "https://media-exp1.licdn.com/dms/image/C5103AQGYZL59gDgP5w/profile-displayphoto-shrink_200_200/0?e=1609372800&v=beta&t=TnHY7yW5Y6MPC2LhlMf6qIlgZYdMo_Y9r6ZFuzJ2LNc",
    "role": "Software Engineer",
    "locality": "Mumbai, MH",
    "country": "India",
    "linkedin": "https://www.linkedin.com/in/dheeraj-bari-b64233110/"
  },
  {
    "value": "Nayan Mewada",
    "text": "Nayan Mewada",
    "email": "nayan.mewada@yapsody.com",
    "image": "https://media-exp1.licdn.com/dms/image/C4D03AQF8pIq0zSWXWw/profile-displayphoto-shrink_200_200/0?e=1609372800&v=beta&t=LLzLkbJavNUdmUjGh7gYXKK629zXwdeILCvuL7g3Iys",
    "role": "Sr. Marketing Manager",
    "locality": "Mumbai, MH",
    "country": "India",
    "facebook": "nayan.mewada",
    "linkedin": "https://www.linkedin.com/in/nayanmewada/"
  },
  {
    "value": "Shreyas Desai",
    "text": "Shreyas Desai",
    "email": "shreyas.desai@yapsody.com",
    "image": "https://media-exp1.licdn.com/dms/image/C4D03AQEy9j5zMhO-Rw/profile-displayphoto-shrink_200_200/0?e=1609372800&v=beta&t=r80zYYb2-2NgFwYArEtZr6ifJPCsGu6jiTG-x8dqxco",
    "role": "Marketing Manager",
    "locality": "Mumbai, MH",
    "country": "India",
    "facebook": "SH2EYAS",
    "twitter": "SH2EYAS",
    "linkedin": "https://www.linkedin.com/in/sh2eyas/"
  },
  {
    "value": "Siddharth Das",
    "text": "Siddharth Das",
    "email": "siddharth.das@yapsody.com",
    "image": "https://media-exp1.licdn.com/dms/image/C5603AQEjZ0cbJQwXkQ/profile-displayphoto-shrink_200_200/0?e=1609372800&v=beta&t=FfNfjdd4rejI4JTqXN1YYdI5nsu3oCmLqh56AkyndOc",
    "role": "Content Marketer",
    "locality": "Mumbai, MH",
    "country": "India",
    "facebook": "dascobar",
    "linkedin": "https://www.linkedin.com/in/siddharth-dasco99/"
  },
  {
    "value": "Aditya Deshpande",
    "text": "Aditya Deshpande",
    "email": "aditya.deshpande@yapsody.com",
    "image":avtar,
    "role": "Social Media Executive",
    "locality": "Mumbai, MH",
    "country": "India"
  },
  {
    "value": "Timothy Fernandes",
    "text": "Timothy Fernandes",
    "email": "timothy.fernandes@yapsody.com",
    "image": "https://media-exp1.licdn.com/dms/image/C5603AQFM_eRsQgdOqQ/profile-displayphoto-shrink_200_200/0?e=1609372800&v=beta&t=XQj_GOZfvlEh8yMvk2vYY5X-SJtBc4D5Rdpe72KEeXA",
    "role": "Client Coordinator",
    "locality": "Mumbai, MH",
    "country": "India",
    "facebook": "timferns90",
    "linkedin": "https://www.linkedin.com/in/timothy-fernandes-☑%EF%B8%8F-61789944/"
  },
  {
    "value": "Jitendra Karanjekar",
    "text": "Jitendra Karanjekar",
    "email": "jitendra.karanjekar@yapsody.com",
    "image": "https://media-exp1.licdn.com/dms/image/C5103AQFXjh-VYMpxUg/profile-displayphoto-shrink_200_200/0?e=1609372800&v=beta&t=RcSJfoxUTam9dCNOtHOKMteM0qnljaZDYIclG2VP9T8",
    "role": "Software Engineer",
    "locality": "Mumbai, MH",
    "country": "India",
    "facebook": "jitendra.karanjekar",
    "linkedin": "https://www.linkedin.com/in/jitendra-karanjekar-a17389168/"
  },
  {
    "value": "Vijay Solanki",
    "text": "Vijay Solanki",
    "email": "vijay.solanki@yapsody.com",
    "image":avtar,
    "role": "Software Engineer",
    "locality": "Mumbai, MH",
    "country": "India"
  },
  {
    "value": "Laxman Pole",
    "text": "Laxman Pole",
    "email": "laxman.pole@yapsody.com",
    "image": "https://media-exp1.licdn.com/dms/image/C5103AQEuGu-HHBIJgw/profile-displayphoto-shrink_200_200/0?e=1609372800&v=beta&t=0CLcBg9ov0U5WlhvaRnyg_tz8hXYgbHgBXi3_zvbAgM",
    "role": "Software Engineer",
    "locality": "Mumbai, MH",
    "country": "India",
    "facebook": "pole.laxman.1",
    "linkedin": "https://www.linkedin.com/in/laxman-pole-538111b0/"
  },
  {
    "value": "Nafis Mansuri",
    "text": "Nafis Mansuri",
    "email": "nafis.mansuri@yapsody.com",
    "image":avtar,
    "role": "QA Engineer",
    "locality": "Mumbai, MH",
    "country": "India",
    "facebook": "nafis.mansuri",
    "linkedin": "https://www.linkedin.com/in/nafis-mansuri-97646b1bb/"
  },
  {
    "value": "Shivkumar Shetty",
    "text": "Shivkumar Shetty",
    "email": "shivkumar.shetty@yapsody.com",
    "image": "https://media-exp1.licdn.com/dms/image/C5103AQFW6B7tzafYzQ/profile-displayphoto-shrink_200_200/0?e=1609372800&v=beta&t=xmV-wkdvUH-d4eeddsNkzjBytMlEsIwzAHXU_4sPOd8",
    "role": "Support Delivery Leader",
    "locality": "Mumbai, MH",
    "country": "India",
    "facebook": "shettyshiva88",
    "linkedin": "https://www.linkedin.com/in/shivkumar-shetty-32666967/"
  },
  {
    "value": "Rohan Chavan",
    "text": "Rohan Chavan",
    "email": "rohan.chavan@yapsody.com",
    "image": "https://media-exp1.licdn.com/dms/image/C5103AQFwpIN6KrWzVA/profile-displayphoto-shrink_200_200/0?e=1609372800&v=beta&t=W1D_Zmrj73xvLQgOTrt4HCnSMazcldL1GmDTIhVPv2A",
    "role": "Support Team Leader",
    "locality": "Mumbai, MH",
    "country": "India",
    "linkedin": "https://www.linkedin.com/in/rohan-chavan-4aa67213/"
  },
  {
    "value": "Sumit Naik",
    "text": "Sumit Naik",
    "email": "sumit.naik@yapsody.com",
    "image":avtar,
    "role": "Sr. Technical Support Professional",
    "locality": "Mumbai, MH",
    "country": "India",
    "facebook": "Sumit.SNaik",
    "linkedin": "https://www.linkedin.com/in/sumit-naik-4398071b9/"
  },
  {
    "value": "Manoj Desai",
    "text": "Manoj Desai",
    "email": "manoj.desai@yapsody.com",
    "image":avtar,
    "role": "Sr. Technical Support Professional",
    "locality": "Mumbai, MH",
    "country": "India",
    "facebook": "manoj.desai.52"
  },
  {
    "value": "Harin Dutia",
    "text": "Harin Dutia",
    "email": "harin.dutia@yapsody.com",
    "image":avtar,
    "role": "Technical Support Professional (Voice & Web Services)",
    "locality": "Mumbai, MH",
    "country": "India"
  },
  {
    "value": "Gilbert Benjamin",
    "text": "Gilbert Benjamin",
    "email": "gilbert.benjamin@yapsody.com",
    "image":avtar,
    "role": "Technical Support Professional (Voice & Web Services)",
    "locality": "Mumbai, MH",
    "country": "India"
  },
  {
    "value": "Rahul Sharma",
    "text": "Rahul Sharma",
    "email": "rahul.sharma@yapsody.com",
    "image":avtar,
    "role": "Technical Support Professional (Voice & Web Services)",
    "locality": "Mumbai, MH",
    "country": "India"
  },
  {
    "value": "Ganesh Puthran",
    "text": "Ganesh Puthran",
    "email": "ganesh.puthran@yapsody.com",
    "image":avtar,
    "role": "Technical Support Professional (Voice & Web Services)",
    "locality": "Mumbai, MH",
    "country": "India"
  },
  {
    "value": "Arjun Agrawal",
    "text": "Arjun Agrawal",
    "email": "arjun.agrawal@yapsody.com",
    "image":avtar,
    "role": "Technical Support Professional (Voice & Web Services)",
    "locality": "Mumbai, MH",
    "country": "India",
    "facebook": "arjun.agrawal50"
  },
  {
    "value": "Ronnie Tattapuram",
    "text": "Ronnie Tattapuram",
    "email": "ronnie.tattapuram@yapsody.com",
    "image":avtar,
    "role": "Support Team Leader",
    "locality": "Mumbai, MH",
    "country": "India",
    "facebook": "https://www.facebook.com/profile.php?id=100000676006513",
    "twitter": "RTattapuram",
    "linkedin": "https://www.linkedin.com/in/ronnie-tattapuram-55505510b/"
  },
  {
    "value": "Clint Dsouza",
    "text": "Clint Dsouza",
    "email": "clint.dsouza@yapsody.com",
    "image":avtar,
    "role": "Customer Support Professional (Voice & Web Services)",
    "locality": "Mumbai, MH",
    "country": "India",
    "linkedin": "https://www.linkedin.com/mwlite/in/clint-dsouza-8229171ba"
  },
  {
    "value": "Sunil Bhalshinge",
    "text": "Sunil Bhalshinge",
    "email": "sunil.bhalshinge@yapsody.com",
    "image":avtar,
    "role": "Customer Support Professional (Voice & Web Services)",
    "locality": "Mumbai, MH",
    "country": "India",
    "facebook": "neil.bhalshinge",
    "linkedin": "https://www.linkedin.com/in/sunil-bhalshinge-18845b19a/"
  },
  {
    "value": "Pradeep Gaikwad",
    "text": "Pradeep Gaikwad",
    "email": "pradeep.gaikwad@yapsody.com",
    "image":avtar,
    "role": "Office Assistant",
    "locality": "Mumbai, MH",
    "country": "India"
  },
  {
    "value": "Avinash Husage",
    "text": "Avinash Husage",
    "email": "avinashhusage@gmail.com",
    "image":avtar,
    "role": "Office Assistant",
    "locality": "Mumbai, MH",
    "country": "India"
  }
]